// Source - https://stackoverflow.com/a/62554326
// Posted by Piyush Agarwal
// Retrieved 2026-05-04, License - CC BY-SA 4.0

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/bike-service-0.0.1-SNAPSHOT.war bike-service-0.0.1-SNAPSHOT.war
artifacts:
  files:
  - bike-service-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*
